# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to preview server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "1.x" ]

  # 手动触发事件
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install pnpm dependencies
      run: pnpm install
    - name: Run build task
      run: pnpm run docs:build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.PREVIEW_SERVER_SSH_PRIVATE_KEY }}
          ARGS: '-avz --delete'
          SOURCE: 'docs/.vuepress/doc/'
          REMOTE_HOST: ${{ secrets.PREVIEW_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.PREVIEW_SERVER_USER }}
          TARGET: '/home/ubuntu/doc/v1'
          EXCLUDE: "/docs/.vuepress/doc/, /node_modules/"
